### PR TITLE
Multiprocessing tokenization

### LINKED ISSUE #64: multi-threading
Currently we're running everything on a single thread. I wonder if there is a straightforward way to provide a wrapper that allows multi-threading (or even distributing) tokenization.

### PR DESCRIPTION
**Pull request by 10zinten**
fix #64

### CODE REVIEW

**Comment by mikkokotila** [comment]
Looks like it will not parallelize properly. 

I'm using the following example from the commit: 

```
from botok import *
profile = "empty"
main, custom = Config().get_tok_data_paths(profile)
tok = Tokenize(Trie(BoSyl, profile, main, custom))
in_str = "མཐའི་བཀྲ་ཤིས། ཀཀ abc མཐའི་རྒྱ་མཚོ་"
preproc = TokChunks(in_str)
preproc.serve_syls_to_trie()
tokens = tok.parallelized_tokenize(preproc)
```

But I'm replacing `in_str` with something like [this volume](https://raw.githubusercontent.com/OpenPecha/P000001/publication/001_%E0%BD%A0%E0%BD%91%E0%BD%B4%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BC%8D_%E0%BD%80.txt).

The result is that the workload occupies only a single thread and wall-clock time is unaffected.

**Comment by 10zinten** [comment]
Interesting, I will look into in soon as possible.

**Comment by 10zinten** [comment]
Interesting, I will look into in soon as possible.

**Comment by mikkokotila** [comment]
Do you have any update available for this?

**Comment by mikkokotila** [comment]
Related to this matter, here is a [working code example](https://github.com/Esukhia/botok/issues/64#issuecomment-667202435) for running Botok in a multiprocessing manner.

**Pull request closed without merging**
